version: 2.1

orbs:
  terraform: circleci/terraform@3.0.1

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          path: ./terraform
          checkout: true
      - terraform/validate:
          path: ./terraform
          checkout: true
          context: aws
          requires:
            - terraform/fmt
      - terraform/plan:
          path: ./terraform
          checkout: true
          context: aws
          persist-workspace: true
          requires:
            - terraform/validate
      - hold:
          type: approval
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
      - terraform/apply:
          path: ./terraform
          attach-workspace: true
          context: aws
          filters:
            branches:
              only: main
          requires:
            - hold
