version: 2.1

orbs:
  node: circleci/node@5.0.2
  terraform: circleci/terraform@3.0.1

jobs:
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      # Checkout the code from the repo
      - checkout
      # Install and cache dependencies from package.json
      - node/install-packages
      # Run the tests
      - run:
          name: Run tests
          command: |
            npm start & 
            npm test

workflows:
  version: 2
  build_node:
    jobs:
      - build
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          path: ./terraform
          checkout: true
      - terraform/validate:
          path: ./terraform
          checkout: true
          context: aws
          requires:
            - terraform/fmt
      - terraform/plan:
          path: ./terraform
          checkout: true
          context: aws
          persist-workspace: true
          requires:
            - terraform/validate
      - hold:
          type: approval
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
      - terraform/apply:
          path: ./terraform
          attach-workspace: true
          context: aws
          filters:
            branches:
              only: main
          requires:
            - hold
